### ISSUE TITLE
出现复制转发udp数据后，目标端口收不到数据的问题

### ISSUE THREAD

**Issue by yi510** [wangbin579/udpcopy#2]
A和B机子内网相通，A开启udpcopy通过内网ip复制9999端口的数据到B的9999，A给自己本身9999端口发数据时能成功实现复制转发，外网给A的9999端口发数据时，B的9999端口无法收到数据，但是在B机子上通过tcpdump指令指定网卡抓端口9999的udp包，还是能抓到复制数据，但就是9999端口接收不到数据（使用python监听9999端口验证的）。如果将./udpcopy -x 9990-ip:9999 ip改为外网端口，则也能正常收到udp数据，请问这是什么原因呢？

**Comment by bluestn** [comment]
我测试了一下，有些网络的安全机制会防止UDP包伪装的功能，发现UDP包的源IP和MAC不符合，直接丢弃了。
